name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          python3-pip \
          python3-dev \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-11-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          libltdl-dev \
          libffi-dev \
          libbz2-dev \
          libreadline-dev \
          libsqlite3-dev \
          libopencv-dev \
          ffmpeg \
          libswscale-dev \
          libavformat-dev \
          libavcodec-dev \
          libsdl2-dev \
          libsdl2-image-dev \
          libsdl2-mixer-dev \
          libsdl2-ttf-dev
    
    - name: Setup directories and permissions
      run: |
        sudo mkdir -p /tmp
        sudo chmod 777 /tmp
        sudo chmod -R 777 .
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        pip install cython buildozer
        pip install --upgrade urllib3==1.26.15
    
    - name: Build APK with Buildozer
      run: |
        # Run buildozer with debug output
        buildozer -v android debug
      timeout-minutes: 60
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: estimatepro-apk
        path: bin/*.apk