name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
      options: --user 0:0 -e HOME=/root
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build APK with Buildozer
      run: |
        # Disable virtualenv to prevent pip --user conflicts
        unset VIRTUAL_ENV
        export PYTHONPATH=
        
        # Run buildozer with verbose output and auto-accept prompts
        yes | buildozer -v android debug
      timeout-minutes: 60
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: estimatepro-apk
        path: bin/*.apk
        retention-days: 30
