name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
      options: --user root
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      run: |
        apt-get update -y
        apt-get install -y python3-pip python3-dev build-essential
    
    - name: Install dependencies
      run: |
        # Disable virtualenv and force system pip
        unset VIRTUAL_ENV
        export PIP_USER=0
        export PYTHONPATH=
        
        # Ensure pip uses system site-packages
        python3 -m pip install --upgrade pip
        python3 -m pip install --no-user appdirs colorama>=0.3.3 jinja2 sh>=1.10,<2.0 build toml packaging setuptools wheel
        
        # Install additional dependencies that might be needed
        apt-get install -y zip unzip openjdk-11-jdk git wget
        
        # Fix potential permission issues
        chmod -R 755 .
    
    - name: Build APK with Buildozer
      run: |
        # Fix permissions
        chmod +x build_apk.sh
        
        # Run buildozer with debug output
        yes | buildozer -v android debug
      timeout-minutes: 60
        
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: estimatepro-apk
        path: bin/*.apk
        retention-days: 30

